name: audio
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  just_audio: ^0.9.37
  file_picker: ^8.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/Cant Stop.mp3

